### ISSUE TITLE
Python 3.5.2 - error - No module named 'gi'

### ISSUE THREAD

**Issue by parsibox** [Nalin-x-Linux/lios-3#3]
```
Traceback (most recent call last):
  File "/usr/bin/lios", line 3, in <module>
    from lios.main import *
  File "/home/parsibox/.virtualenvs/cv/local/lib/python3.5/site-packages/lios/main.py", line 26, in <module>
    from lios import scanner, editor, imageview, cam, ocr, preferences, speech, train_tesseract
  File "/home/parsibox/.virtualenvs/cv/local/lib/python3.5/site-packages/lios/editor.py", line 20, in <module>
    from lios.ui.gtk import text_view, tree_view, widget, dialog, file_chooser, containers, window
  File "/home/parsibox/.virtualenvs/cv/local/lib/python3.5/site-packages/lios/ui/gtk/text_view.py", line 21, in <module>
    from gi.repository import  Gtk
ImportError: No module named 'gi.repository'

```

```
(cv) parsibox@parsibox-VirtualBox:~/Desktop/digit$ pip install gi 
Requirement already satisfied: gi in /home/parsibox/.virtualenvs/cv/lib/python3.5/site-packages
Requirement already satisfied: requests in /home/parsibox/.virtualenvs/cv/lib/python3.5/site-packages (from gi)
```

**Comment by Nalin-x-Linux** [comment]
Try installing dependencies : - python3, python3-imaging-sane | python3-sane, python3-speechd, tesseract-ocr, imagemagick, cuneiform, espeak,poppler-utils, python3-enchant, aspell-en, gir1.2-gst-plugins-base-1.0,gir1.2-gstreamer-1.0 

Also make sure you are using python3
